# Generated by Django 4.0.3 on 2022-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produto_image'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='produto_carrinho', related_query_name='produtos_carrinhos', through='carrinho.Count', to='products.produto'),
        ),
    ]
