# Generated by Django 4.1.4 on 2022-12-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrinho", "0002_alter_carrinho_produtos"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="frete",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="carrinho",
            name="subtotal",
            field=models.IntegerField(default=0),
        ),
    ]
