# Generated by Django 4.1.4 on 2022-12-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carrinho", "0003_carrinho_frete_carrinho_subtotal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinho",
            name="frete",
        ),
        migrations.RemoveField(
            model_name="carrinho",
            name="subtotal",
        ),
    ]
