# Generated by Django 4.0.3 on 2022-12-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_produto_id_alter_produto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
