[package]
name = "PostApp_with_diesel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
clap = "4.1.0"
diesel = "2.0.2"
dotenv = "0.15.0"
package = "0.0.0"
